/*
 * Rinda - B2B Global Sales Automation API
 *
 * B2B 글로벌 세일즈 자동화 플랫폼 - AI 리드 발굴, 이메일 시퀀스 자동화, 리드 관리, IAM, 빌링
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: support@grinda.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostApiV1LeadsBulk200ResponseDuplicateEmailsInner {
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "existingLeadId")]
    pub existing_lead_id: String,
    #[serde(rename = "companyName", skip_serializing_if = "Option::is_none")]
    pub company_name: Option<String>,
    #[serde(
        rename = "existingCompanyName",
        skip_serializing_if = "Option::is_none"
    )]
    pub existing_company_name: Option<String>,
    #[serde(rename = "customerGroupIds", skip_serializing_if = "Option::is_none")]
    pub customer_group_ids: Option<Vec<uuid::Uuid>>,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl PostApiV1LeadsBulk200ResponseDuplicateEmailsInner {
    pub fn new(
        email: String,
        existing_lead_id: String,
        r#type: Type,
    ) -> PostApiV1LeadsBulk200ResponseDuplicateEmailsInner {
        PostApiV1LeadsBulk200ResponseDuplicateEmailsInner {
            email,
            existing_lead_id,
            company_name: None,
            existing_company_name: None,
            customer_group_ids: None,
            r#type,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "database")]
    Database,
    #[serde(rename = "csv")]
    Csv,
}

impl Default for Type {
    fn default() -> Type {
        Self::Database
    }
}
