/*
 * Rinda - B2B Global Sales Automation API
 *
 * B2B 글로벌 세일즈 자동화 플랫폼 - AI 리드 발굴, 이메일 시퀀스 자동화, 리드 관리, IAM, 빌링
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: support@grinda.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostApiV1LeadsBulk200ResponseStats {
    #[serde(rename = "total")]
    pub total: f64,
    #[serde(rename = "created")]
    pub created: f64,
    #[serde(rename = "skipped")]
    pub skipped: f64,
}

impl PostApiV1LeadsBulk200ResponseStats {
    pub fn new(total: f64, created: f64, skipped: f64) -> PostApiV1LeadsBulk200ResponseStats {
        PostApiV1LeadsBulk200ResponseStats {
            total,
            created,
            skipped,
        }
    }
}
