/*
 * Rinda - B2B Global Sales Automation API
 *
 * B2B 글로벌 세일즈 자동화 플랫폼 - AI 리드 발굴, 이메일 시퀀스 자동화, 리드 관리, IAM, 빌링
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: support@grinda.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostApiV1LeadsBulk200ResponseLeadsInnerCreatedAt {
}

impl PostApiV1LeadsBulk200ResponseLeadsInnerCreatedAt {
    pub fn new() -> PostApiV1LeadsBulk200ResponseLeadsInnerCreatedAt {
        PostApiV1LeadsBulk200ResponseLeadsInnerCreatedAt {
        }
    }
}

