/*
 * Rinda - B2B Global Sales Automation API
 *
 * B2B 글로벌 세일즈 자동화 플랫폼 - AI 리드 발굴, 이메일 시퀀스 자동화, 리드 관리, IAM, 빌링
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: support@grinda.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostApiV1VisitorsTrackRequest {
    /// Workspace UUID
    #[serde(rename = "workspaceId")]
    pub workspace_id: String,
    /// Visitor IP address (optional - auto-extracted from CF-Connecting-IP, X-Forwarded-For, or X-Real-IP headers)
    #[serde(rename = "ipAddress", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub ip_address: Option<Option<String>>,
    /// Browser user agent
    #[serde(rename = "userAgent", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub user_agent: Option<Option<String>>,
    /// Referrer URL
    #[serde(rename = "referrer", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub referrer: Option<Option<String>>,
    /// Landing page URL
    #[serde(rename = "landingPage", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub landing_page: Option<Option<String>>,
    /// UTM source parameter
    #[serde(rename = "utmSource", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub utm_source: Option<Option<String>>,
    /// UTM medium parameter
    #[serde(rename = "utmMedium", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub utm_medium: Option<Option<String>>,
    /// UTM campaign parameter
    #[serde(rename = "utmCampaign", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub utm_campaign: Option<Option<String>>,
    /// UTM term parameter
    #[serde(rename = "utmTerm", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub utm_term: Option<Option<String>>,
    /// UTM content parameter
    #[serde(rename = "utmContent", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub utm_content: Option<Option<String>>,
}

impl PostApiV1VisitorsTrackRequest {
    pub fn new(workspace_id: String) -> PostApiV1VisitorsTrackRequest {
        PostApiV1VisitorsTrackRequest {
            workspace_id,
            ip_address: None,
            user_agent: None,
            referrer: None,
            landing_page: None,
            utm_source: None,
            utm_medium: None,
            utm_campaign: None,
            utm_term: None,
            utm_content: None,
        }
    }
}

