/*
 * Rinda - B2B Global Sales Automation API
 *
 * B2B 글로벌 세일즈 자동화 플랫폼 - AI 리드 발굴, 이메일 시퀀스 자동화, 리드 관리, IAM, 빌링
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: support@grinda.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostApiV1LeadsBulk200Response {
    #[serde(rename = "leads")]
    pub leads: Vec<models::PostApiV1LeadsBulk200ResponseLeadsInner>,
    #[serde(rename = "duplicateEmails")]
    pub duplicate_emails: Vec<models::PostApiV1LeadsBulk200ResponseDuplicateEmailsInner>,
    #[serde(rename = "stats")]
    pub stats: Box<models::PostApiV1LeadsBulk200ResponseStats>,
}

impl PostApiV1LeadsBulk200Response {
    pub fn new(leads: Vec<models::PostApiV1LeadsBulk200ResponseLeadsInner>, duplicate_emails: Vec<models::PostApiV1LeadsBulk200ResponseDuplicateEmailsInner>, stats: models::PostApiV1LeadsBulk200ResponseStats) -> PostApiV1LeadsBulk200Response {
        PostApiV1LeadsBulk200Response {
            leads,
            duplicate_emails,
            stats: Box::new(stats),
        }
    }
}

