/*
 * Rinda - B2B Global Sales Automation API
 *
 * B2B 글로벌 세일즈 자동화 플랫폼 - AI 리드 발굴, 이메일 시퀀스 자동화, 리드 관리, IAM, 빌링
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: support@grinda.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostApiV1LeadsBulk200ResponseLeadsInner {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "companyName", deserialize_with = "Option::deserialize")]
    pub company_name: Option<String>,
    #[serde(rename = "foundCompanyName", deserialize_with = "Option::deserialize")]
    pub found_company_name: Option<String>,
    #[serde(rename = "businessType", deserialize_with = "Option::deserialize")]
    pub business_type: Option<String>,
    #[serde(rename = "websiteUrl", deserialize_with = "Option::deserialize")]
    pub website_url: Option<String>,
    #[serde(rename = "description", deserialize_with = "Option::deserialize")]
    pub description: Option<String>,
    #[serde(rename = "country", deserialize_with = "Option::deserialize")]
    pub country: Option<String>,
    #[serde(rename = "city", deserialize_with = "Option::deserialize")]
    pub city: Option<String>,
    #[serde(rename = "leadStatus", deserialize_with = "Option::deserialize")]
    pub lead_status: Option<String>,
    #[serde(rename = "leadScore", deserialize_with = "Option::deserialize")]
    pub lead_score: Option<f64>,
    #[serde(rename = "createdBy", deserialize_with = "Option::deserialize")]
    pub created_by: Option<uuid::Uuid>,
    #[serde(rename = "createdAt")]
    pub created_at: Box<models::PostApiV1LeadsBulk200ResponseLeadsInnerCreatedAt>,
}

impl PostApiV1LeadsBulk200ResponseLeadsInner {
    pub fn new(
        id: uuid::Uuid,
        company_name: Option<String>,
        found_company_name: Option<String>,
        business_type: Option<String>,
        website_url: Option<String>,
        description: Option<String>,
        country: Option<String>,
        city: Option<String>,
        lead_status: Option<String>,
        lead_score: Option<f64>,
        created_by: Option<uuid::Uuid>,
        created_at: models::PostApiV1LeadsBulk200ResponseLeadsInnerCreatedAt,
    ) -> PostApiV1LeadsBulk200ResponseLeadsInner {
        PostApiV1LeadsBulk200ResponseLeadsInner {
            id,
            company_name,
            found_company_name,
            business_type,
            website_url,
            description,
            country,
            city,
            lead_status,
            lead_score,
            created_by,
            created_at: Box::new(created_at),
        }
    }
}
