// Auto-generated SDK client for the Rinda API.
// Generated by progenitor from doc/openapi.json at build time.

include!(concat!(env!("OUT_DIR"), "/codegen.rs"));

#[cfg(test)]
mod tests {
    use super::*;
    use types::GetApiV1LeadsSearchSearchType;

    #[test]
    fn client_new_sets_baseurl() {
        let client = Client::new("https://alpha.rinda.ai/api/v1");
        assert_eq!(client.baseurl(), "https://alpha.rinda.ai/api/v1");
    }

    #[test]
    fn client_new_with_trailing_slash_preserved() {
        let client = Client::new("https://alpha.rinda.ai/api/v1/");
        assert_eq!(client.baseurl(), "https://alpha.rinda.ai/api/v1/");
    }

    #[test]
    fn client_new_with_custom_reqwest_client() {
        let reqwest_client = reqwest::ClientBuilder::new()
            .timeout(std::time::Duration::from_secs(30))
            .build()
            .unwrap();
        let client = Client::new_with_client("https://alpha.rinda.ai/api/v1", reqwest_client);
        assert_eq!(client.baseurl(), "https://alpha.rinda.ai/api/v1");
    }

    #[test]
    fn api_version_is_set() {
        // Verify the spec declares an API version.
        let version = Client::api_version();
        assert!(!version.is_empty(), "api_version should not be empty");
    }

    #[test]
    fn leads_search_type_variants_exist() {
        // Verify key enums are generated and usable.
        let _all = GetApiV1LeadsSearchSearchType::All;
        let _company = GetApiV1LeadsSearchSearchType::Company;
    }

    #[test]
    fn search_type_enum_serializes_correctly() {
        let val = GetApiV1LeadsSearchSearchType::Company;
        assert_eq!(val.to_string(), "company");

        let parsed: GetApiV1LeadsSearchSearchType = "email".parse().unwrap();
        assert!(matches!(parsed, GetApiV1LeadsSearchSearchType::Email));
    }
}
