/*
 * Rinda - B2B Global Sales Automation API
 *
 * B2B 글로벌 세일즈 자동화 플랫폼 - AI 리드 발굴, 이메일 시퀀스 자동화, 리드 관리, IAM, 빌링
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: support@grinda.ai
 * Generated by: https://openapi-generator.tech
 */

use super::{ContentType, Error, configuration};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};

/// struct for typed errors of method [`get_api_v1_leads_search`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetApiV1LeadsSearchError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`post_api_v1_leads_bulk`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PostApiV1LeadsBulkError {
    UnknownValue(serde_json::Value),
}

/// Search and filter leads with support for column-specific filters, sorting, pagination, and date ranges. Filters parameter accepts JSON array of filter objects with field, operator, and value properties. Supported operators: equals, notEquals, contains, startsWith, endsWith, gt, lt, gte, lte, between, in, notIn, isEmpty, isNotEmpty. Example: [{\"field\":\"leadScore\",\"operator\":\"gt\",\"value\":80},{\"field\":\"country\",\"operator\":\"in\",\"value\":[\"USA\",\"Canada\"]}]
pub async fn get_api_v1_leads_search(
    configuration: &configuration::Configuration,
    limit: Option<&str>,
    offset: Option<&str>,
    lead_status: Option<&str>,
    business_type: Option<&str>,
    country: Option<&str>,
    city: Option<&str>,
    search: Option<&str>,
    search_type: Option<&str>,
    workspace_ids: Option<&str>,
    created_by_ids: Option<&str>,
    customer_group_id: Option<&str>,
    filters: Option<&str>,
    sort_field: Option<&str>,
    sort_order: Option<&str>,
    created_after: Option<&str>,
    created_before: Option<&str>,
    updated_after: Option<&str>,
    updated_before: Option<&str>,
) -> Result<std::collections::HashMap<String, serde_json::Value>, Error<GetApiV1LeadsSearchError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_limit = limit;
    let p_query_offset = offset;
    let p_query_lead_status = lead_status;
    let p_query_business_type = business_type;
    let p_query_country = country;
    let p_query_city = city;
    let p_query_search = search;
    let p_query_search_type = search_type;
    let p_query_workspace_ids = workspace_ids;
    let p_query_created_by_ids = created_by_ids;
    let p_query_customer_group_id = customer_group_id;
    let p_query_filters = filters;
    let p_query_sort_field = sort_field;
    let p_query_sort_order = sort_order;
    let p_query_created_after = created_after;
    let p_query_created_before = created_before;
    let p_query_updated_after = updated_after;
    let p_query_updated_before = updated_before;

    let uri_str = format!("{}/api/v1/leads/search", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_limit {
        req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_offset {
        req_builder = req_builder.query(&[("offset", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_lead_status {
        req_builder = req_builder.query(&[("leadStatus", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_business_type {
        req_builder = req_builder.query(&[("businessType", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_country {
        req_builder = req_builder.query(&[("country", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_city {
        req_builder = req_builder.query(&[("city", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_search {
        req_builder = req_builder.query(&[("search", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_search_type {
        req_builder = req_builder.query(&[("searchType", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_workspace_ids {
        req_builder = req_builder.query(&[("workspaceIds", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_created_by_ids {
        req_builder = req_builder.query(&[("createdByIds", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_customer_group_id {
        req_builder = req_builder.query(&[("customerGroupId", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_filters {
        req_builder = req_builder.query(&[("filters", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_sort_field {
        req_builder = req_builder.query(&[("sortField", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_sort_order {
        req_builder = req_builder.query(&[("sortOrder", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_created_after {
        req_builder = req_builder.query(&[("createdAfter", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_created_before {
        req_builder = req_builder.query(&[("createdBefore", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_updated_after {
        req_builder = req_builder.query(&[("updatedAfter", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_updated_before {
        req_builder = req_builder.query(&[("updatedBefore", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `std::collections::HashMap&lt;String, serde_json::Value&gt;`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `std::collections::HashMap&lt;String, serde_json::Value&gt;`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetApiV1LeadsSearchError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// JSON 배열로 여러 리드를 일괄 생성합니다. 중복 이메일 방지: (1) 요청 데이터 내부의 중복 이메일과 (2) Workspace 내 기존 데이터베이스의 중복 이메일이 자동으로 감지되어 스킵됩니다. 응답에는 생성된 리드 목록, 중복 이메일 상세정보(email, existingLeadId, companyName, existingCompanyName, customerGroupIds, type), 통계(total, created, skipped)가 포함됩니다. 중복 감지 시 기존 리드의 회사명과 소속 고객 그룹 정보도 함께 반환됩니다. 선택적으로 고객 그룹에 자동 추가할 수 있습니다.
pub async fn post_api_v1_leads_bulk(
    configuration: &configuration::Configuration,
    request_body: std::collections::HashMap<String, serde_json::Value>,
) -> Result<models::PostApiV1LeadsBulk200Response, Error<PostApiV1LeadsBulkError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_request_body = request_body;

    let uri_str = format!("{}/api/v1/leads/bulk", configuration.base_path);
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_request_body);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::PostApiV1LeadsBulk200Response`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::PostApiV1LeadsBulk200Response`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<PostApiV1LeadsBulkError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
