/*
 * Rinda - B2B Global Sales Automation API
 *
 * B2B 글로벌 세일즈 자동화 플랫폼 - AI 리드 발굴, 이메일 시퀀스 자동화, 리드 관리, IAM, 빌링
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: support@grinda.ai
 * Generated by: https://openapi-generator.tech
 */

use super::{ContentType, Error, configuration};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};

/// struct for typed errors of method [`delete_api_v1_admin_trial_analytics_exclusions`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteApiV1AdminTrialAnalyticsExclusionsError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_api_v1_admin_trial_analytics_exclusions_by_workspace_id`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteApiV1AdminTrialAnalyticsExclusionsByWorkspaceIdError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_api_v1_admin_trial_analytics`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetApiV1AdminTrialAnalyticsError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_api_v1_admin_trial_analytics_email_performance_csv`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetApiV1AdminTrialAnalyticsEmailPerformanceCsvError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_api_v1_admin_trial_analytics_exclusions`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetApiV1AdminTrialAnalyticsExclusionsError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_api_v1_admin_trial_analytics_feature_usage_by_workspace_id`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetApiV1AdminTrialAnalyticsFeatureUsageByWorkspaceIdError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_api_v1_admin_trial_analytics_onboarding_by_step`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetApiV1AdminTrialAnalyticsOnboardingByStepError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_api_v1_admin_trial_analytics_users`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetApiV1AdminTrialAnalyticsUsersError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_api_v1_admin_trial_analytics_workspaces_for_exclusion`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetApiV1AdminTrialAnalyticsWorkspacesForExclusionError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`patch_api_v1_admin_trial_analytics_feature_usage`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PatchApiV1AdminTrialAnalyticsFeatureUsageError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`post_api_v1_admin_trial_analytics_bulk_extend`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PostApiV1AdminTrialAnalyticsBulkExtendError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`post_api_v1_admin_trial_analytics_exclusions`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PostApiV1AdminTrialAnalyticsExclusionsError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`post_api_v1_admin_trial_analytics_exclusions_bulk`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PostApiV1AdminTrialAnalyticsExclusionsBulkError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`post_api_v1_admin_trial_analytics_extend`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PostApiV1AdminTrialAnalyticsExtendError {
    UnknownValue(serde_json::Value),
}

/// 모든 워크스페이스 제외 설정을 초기화
pub async fn delete_api_v1_admin_trial_analytics_exclusions(
    configuration: &configuration::Configuration,
) -> Result<
    std::collections::HashMap<String, serde_json::Value>,
    Error<DeleteApiV1AdminTrialAnalyticsExclusionsError>,
> {
    let uri_str = format!(
        "{}/api/v1/admin/trial-analytics/exclusions",
        configuration.base_path
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `std::collections::HashMap&lt;String, serde_json::Value&gt;`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `std::collections::HashMap&lt;String, serde_json::Value&gt;`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteApiV1AdminTrialAnalyticsExclusionsError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// 워크스페이스를 통계에 다시 포함
pub async fn delete_api_v1_admin_trial_analytics_exclusions_by_workspace_id(
    configuration: &configuration::Configuration,
    workspace_id: &str,
) -> Result<
    std::collections::HashMap<String, serde_json::Value>,
    Error<DeleteApiV1AdminTrialAnalyticsExclusionsByWorkspaceIdError>,
> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_workspace_id = workspace_id;

    let uri_str = format!(
        "{}/api/v1/admin/trial-analytics/exclusions/{workspaceId}",
        configuration.base_path,
        workspaceId = crate::apis::urlencode(p_path_workspace_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `std::collections::HashMap&lt;String, serde_json::Value&gt;`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `std::collections::HashMap&lt;String, serde_json::Value&gt;`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteApiV1AdminTrialAnalyticsExclusionsByWorkspaceIdError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// KPI 요약, 가입 추이, 온보딩 퍼널, 성과 분포 등 차트 데이터 조회. 제외 목록은 DB에서 자동 적용
pub async fn get_api_v1_admin_trial_analytics(
    configuration: &configuration::Configuration,
    days: Option<&str>,
    cohort_mode: Option<&str>,
) -> Result<
    std::collections::HashMap<String, serde_json::Value>,
    Error<GetApiV1AdminTrialAnalyticsError>,
> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_days = days;
    let p_query_cohort_mode = cohort_mode;

    let uri_str = format!("{}/api/v1/admin/trial-analytics/", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_days {
        req_builder = req_builder.query(&[("days", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_cohort_mode {
        req_builder = req_builder.query(&[("cohortMode", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `std::collections::HashMap&lt;String, serde_json::Value&gt;`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `std::collections::HashMap&lt;String, serde_json::Value&gt;`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetApiV1AdminTrialAnalyticsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// 체험판 워크스페이스 이메일 성과 데이터를 CSV 파일로 다운로드 (전체 기간, 제외 목록 적용)
pub async fn get_api_v1_admin_trial_analytics_email_performance_csv(
    configuration: &configuration::Configuration,
) -> Result<
    std::collections::HashMap<String, serde_json::Value>,
    Error<GetApiV1AdminTrialAnalyticsEmailPerformanceCsvError>,
> {
    let uri_str = format!(
        "{}/api/v1/admin/trial-analytics/email-performance/csv",
        configuration.base_path
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `std::collections::HashMap&lt;String, serde_json::Value&gt;`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `std::collections::HashMap&lt;String, serde_json::Value&gt;`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetApiV1AdminTrialAnalyticsEmailPerformanceCsvError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// 통계에서 제외된 워크스페이스 목록 조회
pub async fn get_api_v1_admin_trial_analytics_exclusions(
    configuration: &configuration::Configuration,
) -> Result<
    std::collections::HashMap<String, serde_json::Value>,
    Error<GetApiV1AdminTrialAnalyticsExclusionsError>,
> {
    let uri_str = format!(
        "{}/api/v1/admin/trial-analytics/exclusions",
        configuration.base_path
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `std::collections::HashMap&lt;String, serde_json::Value&gt;`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `std::collections::HashMap&lt;String, serde_json::Value&gt;`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetApiV1AdminTrialAnalyticsExclusionsError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// 워크스페이스의 기능별 사용량 조회
pub async fn get_api_v1_admin_trial_analytics_feature_usage_by_workspace_id(
    configuration: &configuration::Configuration,
    workspace_id: &str,
) -> Result<
    std::collections::HashMap<String, serde_json::Value>,
    Error<GetApiV1AdminTrialAnalyticsFeatureUsageByWorkspaceIdError>,
> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_workspace_id = workspace_id;

    let uri_str = format!(
        "{}/api/v1/admin/trial-analytics/feature-usage/{workspaceId}",
        configuration.base_path,
        workspaceId = crate::apis::urlencode(p_path_workspace_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `std::collections::HashMap&lt;String, serde_json::Value&gt;`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `std::collections::HashMap&lt;String, serde_json::Value&gt;`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetApiV1AdminTrialAnalyticsFeatureUsageByWorkspaceIdError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// 특정 퍼널 단계에 해당하는 워크스페이스 목록 조회
pub async fn get_api_v1_admin_trial_analytics_onboarding_by_step(
    configuration: &configuration::Configuration,
    step: &str,
) -> Result<
    std::collections::HashMap<String, serde_json::Value>,
    Error<GetApiV1AdminTrialAnalyticsOnboardingByStepError>,
> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_step = step;

    let uri_str = format!(
        "{}/api/v1/admin/trial-analytics/onboarding/{step}",
        configuration.base_path,
        step = crate::apis::urlencode(p_path_step)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `std::collections::HashMap&lt;String, serde_json::Value&gt;`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `std::collections::HashMap&lt;String, serde_json::Value&gt;`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetApiV1AdminTrialAnalyticsOnboardingByStepError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// 페이지네이션, 필터, 정렬 지원
pub async fn get_api_v1_admin_trial_analytics_users(
    configuration: &configuration::Configuration,
    page: Option<&str>,
    limit: Option<&str>,
    sort_by: Option<&str>,
    sort_order: Option<&str>,
    status: Option<&str>,
    onboarding_status: Option<&str>,
    auth_provider: Option<&str>,
) -> Result<
    std::collections::HashMap<String, serde_json::Value>,
    Error<GetApiV1AdminTrialAnalyticsUsersError>,
> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_page = page;
    let p_query_limit = limit;
    let p_query_sort_by = sort_by;
    let p_query_sort_order = sort_order;
    let p_query_status = status;
    let p_query_onboarding_status = onboarding_status;
    let p_query_auth_provider = auth_provider;

    let uri_str = format!(
        "{}/api/v1/admin/trial-analytics/users",
        configuration.base_path
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_page {
        req_builder = req_builder.query(&[("page", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_limit {
        req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_sort_by {
        req_builder = req_builder.query(&[("sortBy", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_sort_order {
        req_builder = req_builder.query(&[("sortOrder", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_status {
        req_builder = req_builder.query(&[("status", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_onboarding_status {
        req_builder = req_builder.query(&[("onboardingStatus", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_auth_provider {
        req_builder = req_builder.query(&[("authProvider", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `std::collections::HashMap&lt;String, serde_json::Value&gt;`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `std::collections::HashMap&lt;String, serde_json::Value&gt;`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetApiV1AdminTrialAnalyticsUsersError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// 제외 설정 모달에서 사용할 워크스페이스 목록. 비제외 항목은 최신 가입순, 제외 항목은 맨 아래 표시
pub async fn get_api_v1_admin_trial_analytics_workspaces_for_exclusion(
    configuration: &configuration::Configuration,
) -> Result<
    std::collections::HashMap<String, serde_json::Value>,
    Error<GetApiV1AdminTrialAnalyticsWorkspacesForExclusionError>,
> {
    let uri_str = format!(
        "{}/api/v1/admin/trial-analytics/workspaces-for-exclusion",
        configuration.base_path
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `std::collections::HashMap&lt;String, serde_json::Value&gt;`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `std::collections::HashMap&lt;String, serde_json::Value&gt;`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetApiV1AdminTrialAnalyticsWorkspacesForExclusionError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// 워크스페이스의 기능 사용 횟수를 직접 변경 (관리자 전용)
pub async fn patch_api_v1_admin_trial_analytics_feature_usage(
    configuration: &configuration::Configuration,
    request_body: std::collections::HashMap<String, serde_json::Value>,
) -> Result<
    std::collections::HashMap<String, serde_json::Value>,
    Error<PatchApiV1AdminTrialAnalyticsFeatureUsageError>,
> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_request_body = request_body;

    let uri_str = format!(
        "{}/api/v1/admin/trial-analytics/feature-usage",
        configuration.base_path
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::PATCH, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_request_body);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `std::collections::HashMap&lt;String, serde_json::Value&gt;`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `std::collections::HashMap&lt;String, serde_json::Value&gt;`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<PatchApiV1AdminTrialAnalyticsFeatureUsageError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// 여러 워크스페이스의 체험판 기간을 일괄 연장합니다
pub async fn post_api_v1_admin_trial_analytics_bulk_extend(
    configuration: &configuration::Configuration,
    request_body: std::collections::HashMap<String, serde_json::Value>,
) -> Result<
    std::collections::HashMap<String, serde_json::Value>,
    Error<PostApiV1AdminTrialAnalyticsBulkExtendError>,
> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_request_body = request_body;

    let uri_str = format!(
        "{}/api/v1/admin/trial-analytics/bulk-extend",
        configuration.base_path
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_request_body);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `std::collections::HashMap&lt;String, serde_json::Value&gt;`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `std::collections::HashMap&lt;String, serde_json::Value&gt;`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<PostApiV1AdminTrialAnalyticsBulkExtendError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// 워크스페이스를 통계에서 제외
pub async fn post_api_v1_admin_trial_analytics_exclusions(
    configuration: &configuration::Configuration,
    request_body: std::collections::HashMap<String, serde_json::Value>,
) -> Result<
    std::collections::HashMap<String, serde_json::Value>,
    Error<PostApiV1AdminTrialAnalyticsExclusionsError>,
> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_request_body = request_body;

    let uri_str = format!(
        "{}/api/v1/admin/trial-analytics/exclusions",
        configuration.base_path
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_request_body);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `std::collections::HashMap&lt;String, serde_json::Value&gt;`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `std::collections::HashMap&lt;String, serde_json::Value&gt;`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<PostApiV1AdminTrialAnalyticsExclusionsError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// 여러 워크스페이스를 통계에서 일괄 제외
pub async fn post_api_v1_admin_trial_analytics_exclusions_bulk(
    configuration: &configuration::Configuration,
    request_body: std::collections::HashMap<String, serde_json::Value>,
) -> Result<
    std::collections::HashMap<String, serde_json::Value>,
    Error<PostApiV1AdminTrialAnalyticsExclusionsBulkError>,
> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_request_body = request_body;

    let uri_str = format!(
        "{}/api/v1/admin/trial-analytics/exclusions/bulk",
        configuration.base_path
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_request_body);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `std::collections::HashMap&lt;String, serde_json::Value&gt;`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `std::collections::HashMap&lt;String, serde_json::Value&gt;`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<PostApiV1AdminTrialAnalyticsExclusionsBulkError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// 특정 워크스페이스의 체험판 기간을 연장합니다
pub async fn post_api_v1_admin_trial_analytics_extend(
    configuration: &configuration::Configuration,
    request_body: std::collections::HashMap<String, serde_json::Value>,
) -> Result<
    std::collections::HashMap<String, serde_json::Value>,
    Error<PostApiV1AdminTrialAnalyticsExtendError>,
> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_request_body = request_body;

    let uri_str = format!(
        "{}/api/v1/admin/trial-analytics/extend",
        configuration.base_path
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_request_body);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `std::collections::HashMap&lt;String, serde_json::Value&gt;`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `std::collections::HashMap&lt;String, serde_json::Value&gt;`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<PostApiV1AdminTrialAnalyticsExtendError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
