/*
 * Rinda - B2B Global Sales Automation API
 *
 * B2B 글로벌 세일즈 자동화 플랫폼 - AI 리드 발굴, 이메일 시퀀스 자동화, 리드 관리, IAM, 빌링
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: support@grinda.ai
 * Generated by: https://openapi-generator.tech
 */

use super::{ContentType, Error, configuration};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};

/// struct for typed errors of method [`delete_api_v1_workspaces_by_id_visitors_cleanup`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteApiV1WorkspacesByIdVisitorsCleanupError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_api_v1_workspaces_by_id_visitors_excluded_companies_by_excluded_id`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteApiV1WorkspacesByIdVisitorsExcludedCompaniesByExcludedIdError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_api_v1_visitors`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetApiV1VisitorsError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_api_v1_visitors_companies_for_exclusion`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetApiV1VisitorsCompaniesForExclusionError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_api_v1_visitors_countries`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetApiV1VisitorsCountriesError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_api_v1_visitors_excluded_companies`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetApiV1VisitorsExcludedCompaniesError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_api_v1_visitors_stats`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetApiV1VisitorsStatsError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_api_v1_workspaces_by_id_visitors`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetApiV1WorkspacesByIdVisitorsError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_api_v1_workspaces_by_id_visitors_by_visitor_id`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetApiV1WorkspacesByIdVisitorsByVisitorIdError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_api_v1_workspaces_by_id_visitors_companies_for_exclusion`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetApiV1WorkspacesByIdVisitorsCompaniesForExclusionError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_api_v1_workspaces_by_id_visitors_countries`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetApiV1WorkspacesByIdVisitorsCountriesError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_api_v1_workspaces_by_id_visitors_excluded_companies`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetApiV1WorkspacesByIdVisitorsExcludedCompaniesError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_api_v1_workspaces_by_id_visitors_stats`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetApiV1WorkspacesByIdVisitorsStatsError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`post_api_v1_visitors_track`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PostApiV1VisitorsTrackError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`post_api_v1_workspaces_by_id_visitors_excluded_companies`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PostApiV1WorkspacesByIdVisitorsExcludedCompaniesError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`post_api_v1_workspaces_by_id_visitors_excluded_companies_bulk`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PostApiV1WorkspacesByIdVisitorsExcludedCompaniesBulkError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`post_api_v1_workspaces_by_id_visitors_sync_to_leads`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PostApiV1WorkspacesByIdVisitorsSyncToLeadsError {
    UnknownValue(serde_json::Value),
}

/// Delete visitor sessions older than specified days for GDPR compliance.
pub async fn delete_api_v1_workspaces_by_id_visitors_cleanup(
    configuration: &configuration::Configuration,
    id: &str,
    days_old: Option<&str>,
) -> Result<
    std::collections::HashMap<String, serde_json::Value>,
    Error<DeleteApiV1WorkspacesByIdVisitorsCleanupError>,
> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_id = id;
    let p_query_days_old = days_old;

    let uri_str = format!(
        "{}/api/v1/workspaces/{id}/visitors/cleanup",
        configuration.base_path,
        id = crate::apis::urlencode(p_path_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref param_value) = p_query_days_old {
        req_builder = req_builder.query(&[("daysOld", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `std::collections::HashMap&lt;String, serde_json::Value&gt;`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `std::collections::HashMap&lt;String, serde_json::Value&gt;`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteApiV1WorkspacesByIdVisitorsCleanupError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Remove a company from the exclusion list for visitor analytics.
pub async fn delete_api_v1_workspaces_by_id_visitors_excluded_companies_by_excluded_id(
    configuration: &configuration::Configuration,
    id: &str,
    excluded_id: &str,
) -> Result<
    std::collections::HashMap<String, serde_json::Value>,
    Error<DeleteApiV1WorkspacesByIdVisitorsExcludedCompaniesByExcludedIdError>,
> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_id = id;
    let p_path_excluded_id = excluded_id;

    let uri_str = format!(
        "{}/api/v1/workspaces/{id}/visitors/excluded-companies/{excludedId}",
        configuration.base_path,
        id = crate::apis::urlencode(p_path_id),
        excludedId = crate::apis::urlencode(p_path_excluded_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `std::collections::HashMap&lt;String, serde_json::Value&gt;`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `std::collections::HashMap&lt;String, serde_json::Value&gt;`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteApiV1WorkspacesByIdVisitorsExcludedCompaniesByExcludedIdError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// List visitor sessions with optional workspace filter. Use workspaceId=\"all\" or omit for all workspaces (admin only).
pub async fn get_api_v1_visitors(
    configuration: &configuration::Configuration,
    workspace_id: Option<&str>,
    limit: Option<&str>,
    offset: Option<&str>,
    search: Option<&str>,
    countries: Option<&str>,
    has_company: Option<&str>,
    security_flags: Option<&str>,
    date_from: Option<&str>,
    date_to: Option<&str>,
    sort_by: Option<&str>,
    sort_order: Option<&str>,
    exclude_isp: Option<&str>,
    exclude_hosting: Option<&str>,
    exclude_datacenter: Option<&str>,
    exclude_suspicious: Option<&str>,
) -> Result<std::collections::HashMap<String, serde_json::Value>, Error<GetApiV1VisitorsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_workspace_id = workspace_id;
    let p_query_limit = limit;
    let p_query_offset = offset;
    let p_query_search = search;
    let p_query_countries = countries;
    let p_query_has_company = has_company;
    let p_query_security_flags = security_flags;
    let p_query_date_from = date_from;
    let p_query_date_to = date_to;
    let p_query_sort_by = sort_by;
    let p_query_sort_order = sort_order;
    let p_query_exclude_isp = exclude_isp;
    let p_query_exclude_hosting = exclude_hosting;
    let p_query_exclude_datacenter = exclude_datacenter;
    let p_query_exclude_suspicious = exclude_suspicious;

    let uri_str = format!("{}/api/v1/visitors/", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_workspace_id {
        req_builder = req_builder.query(&[("workspaceId", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_limit {
        req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_offset {
        req_builder = req_builder.query(&[("offset", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_search {
        req_builder = req_builder.query(&[("search", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_countries {
        req_builder = req_builder.query(&[("countries", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_has_company {
        req_builder = req_builder.query(&[("hasCompany", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_security_flags {
        req_builder = req_builder.query(&[("securityFlags", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_date_from {
        req_builder = req_builder.query(&[("dateFrom", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_date_to {
        req_builder = req_builder.query(&[("dateTo", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_sort_by {
        req_builder = req_builder.query(&[("sortBy", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_sort_order {
        req_builder = req_builder.query(&[("sortOrder", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_exclude_isp {
        req_builder = req_builder.query(&[("excludeIsp", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_exclude_hosting {
        req_builder = req_builder.query(&[("excludeHosting", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_exclude_datacenter {
        req_builder = req_builder.query(&[("excludeDatacenter", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_exclude_suspicious {
        req_builder = req_builder.query(&[("excludeSuspicious", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `std::collections::HashMap&lt;String, serde_json::Value&gt;`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `std::collections::HashMap&lt;String, serde_json::Value&gt;`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetApiV1VisitorsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Get list of companies from visitor data for exclusion dropdown.
pub async fn get_api_v1_visitors_companies_for_exclusion(
    configuration: &configuration::Configuration,
    workspace_id: Option<&str>,
    search: Option<&str>,
    limit: Option<&str>,
) -> Result<
    std::collections::HashMap<String, serde_json::Value>,
    Error<GetApiV1VisitorsCompaniesForExclusionError>,
> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_workspace_id = workspace_id;
    let p_query_search = search;
    let p_query_limit = limit;

    let uri_str = format!(
        "{}/api/v1/visitors/companies-for-exclusion",
        configuration.base_path
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_workspace_id {
        req_builder = req_builder.query(&[("workspaceId", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_search {
        req_builder = req_builder.query(&[("search", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_limit {
        req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `std::collections::HashMap&lt;String, serde_json::Value&gt;`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `std::collections::HashMap&lt;String, serde_json::Value&gt;`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetApiV1VisitorsCompaniesForExclusionError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Get list of unique countries from visitor sessions for filter dropdown.
pub async fn get_api_v1_visitors_countries(
    configuration: &configuration::Configuration,
    workspace_id: Option<&str>,
) -> Result<
    std::collections::HashMap<String, serde_json::Value>,
    Error<GetApiV1VisitorsCountriesError>,
> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_workspace_id = workspace_id;

    let uri_str = format!("{}/api/v1/visitors/countries", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_workspace_id {
        req_builder = req_builder.query(&[("workspaceId", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `std::collections::HashMap&lt;String, serde_json::Value&gt;`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `std::collections::HashMap&lt;String, serde_json::Value&gt;`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetApiV1VisitorsCountriesError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Get list of companies excluded from visitor analytics.
pub async fn get_api_v1_visitors_excluded_companies(
    configuration: &configuration::Configuration,
    workspace_id: Option<&str>,
) -> Result<
    std::collections::HashMap<String, serde_json::Value>,
    Error<GetApiV1VisitorsExcludedCompaniesError>,
> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_workspace_id = workspace_id;

    let uri_str = format!(
        "{}/api/v1/visitors/excluded-companies",
        configuration.base_path
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_workspace_id {
        req_builder = req_builder.query(&[("workspaceId", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `std::collections::HashMap&lt;String, serde_json::Value&gt;`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `std::collections::HashMap&lt;String, serde_json::Value&gt;`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetApiV1VisitorsExcludedCompaniesError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Get aggregated visitor statistics. Use workspaceId=\"all\" or omit for all workspaces.
pub async fn get_api_v1_visitors_stats(
    configuration: &configuration::Configuration,
    workspace_id: Option<&str>,
    days: Option<&str>,
) -> Result<std::collections::HashMap<String, serde_json::Value>, Error<GetApiV1VisitorsStatsError>>
{
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_workspace_id = workspace_id;
    let p_query_days = days;

    let uri_str = format!("{}/api/v1/visitors/stats", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_workspace_id {
        req_builder = req_builder.query(&[("workspaceId", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_days {
        req_builder = req_builder.query(&[("days", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `std::collections::HashMap&lt;String, serde_json::Value&gt;`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `std::collections::HashMap&lt;String, serde_json::Value&gt;`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetApiV1VisitorsStatsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// List all visitor sessions for a workspace with pagination, search, and filters.
pub async fn get_api_v1_workspaces_by_id_visitors(
    configuration: &configuration::Configuration,
    id: &str,
    limit: Option<&str>,
    offset: Option<&str>,
    search: Option<&str>,
    countries: Option<&str>,
    has_company: Option<&str>,
    security_flags: Option<&str>,
    date_from: Option<&str>,
    date_to: Option<&str>,
    sort_by: Option<&str>,
    sort_order: Option<&str>,
    exclude_isp: Option<&str>,
    exclude_hosting: Option<&str>,
    exclude_datacenter: Option<&str>,
    exclude_suspicious: Option<&str>,
) -> Result<
    std::collections::HashMap<String, serde_json::Value>,
    Error<GetApiV1WorkspacesByIdVisitorsError>,
> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_id = id;
    let p_query_limit = limit;
    let p_query_offset = offset;
    let p_query_search = search;
    let p_query_countries = countries;
    let p_query_has_company = has_company;
    let p_query_security_flags = security_flags;
    let p_query_date_from = date_from;
    let p_query_date_to = date_to;
    let p_query_sort_by = sort_by;
    let p_query_sort_order = sort_order;
    let p_query_exclude_isp = exclude_isp;
    let p_query_exclude_hosting = exclude_hosting;
    let p_query_exclude_datacenter = exclude_datacenter;
    let p_query_exclude_suspicious = exclude_suspicious;

    let uri_str = format!(
        "{}/api/v1/workspaces/{id}/visitors/",
        configuration.base_path,
        id = crate::apis::urlencode(p_path_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_limit {
        req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_offset {
        req_builder = req_builder.query(&[("offset", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_search {
        req_builder = req_builder.query(&[("search", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_countries {
        req_builder = req_builder.query(&[("countries", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_has_company {
        req_builder = req_builder.query(&[("hasCompany", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_security_flags {
        req_builder = req_builder.query(&[("securityFlags", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_date_from {
        req_builder = req_builder.query(&[("dateFrom", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_date_to {
        req_builder = req_builder.query(&[("dateTo", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_sort_by {
        req_builder = req_builder.query(&[("sortBy", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_sort_order {
        req_builder = req_builder.query(&[("sortOrder", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_exclude_isp {
        req_builder = req_builder.query(&[("excludeIsp", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_exclude_hosting {
        req_builder = req_builder.query(&[("excludeHosting", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_exclude_datacenter {
        req_builder = req_builder.query(&[("excludeDatacenter", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_exclude_suspicious {
        req_builder = req_builder.query(&[("excludeSuspicious", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `std::collections::HashMap&lt;String, serde_json::Value&gt;`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `std::collections::HashMap&lt;String, serde_json::Value&gt;`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetApiV1WorkspacesByIdVisitorsError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Get detailed information about a specific visitor session.
pub async fn get_api_v1_workspaces_by_id_visitors_by_visitor_id(
    configuration: &configuration::Configuration,
    id: &str,
    visitor_id: &str,
) -> Result<
    std::collections::HashMap<String, serde_json::Value>,
    Error<GetApiV1WorkspacesByIdVisitorsByVisitorIdError>,
> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_id = id;
    let p_path_visitor_id = visitor_id;

    let uri_str = format!(
        "{}/api/v1/workspaces/{id}/visitors/{visitorId}",
        configuration.base_path,
        id = crate::apis::urlencode(p_path_id),
        visitorId = crate::apis::urlencode(p_path_visitor_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `std::collections::HashMap&lt;String, serde_json::Value&gt;`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `std::collections::HashMap&lt;String, serde_json::Value&gt;`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetApiV1WorkspacesByIdVisitorsByVisitorIdError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Get list of companies from visitor data for exclusion dropdown. Returns companies with visitor count and current exclusion status.
pub async fn get_api_v1_workspaces_by_id_visitors_companies_for_exclusion(
    configuration: &configuration::Configuration,
    id: &str,
    search: Option<&str>,
    limit: Option<&str>,
) -> Result<
    std::collections::HashMap<String, serde_json::Value>,
    Error<GetApiV1WorkspacesByIdVisitorsCompaniesForExclusionError>,
> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_id = id;
    let p_query_search = search;
    let p_query_limit = limit;

    let uri_str = format!(
        "{}/api/v1/workspaces/{id}/visitors/companies-for-exclusion",
        configuration.base_path,
        id = crate::apis::urlencode(p_path_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_search {
        req_builder = req_builder.query(&[("search", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_limit {
        req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `std::collections::HashMap&lt;String, serde_json::Value&gt;`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `std::collections::HashMap&lt;String, serde_json::Value&gt;`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetApiV1WorkspacesByIdVisitorsCompaniesForExclusionError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Get list of unique countries from visitor sessions for filter dropdown.
pub async fn get_api_v1_workspaces_by_id_visitors_countries(
    configuration: &configuration::Configuration,
    id: &str,
) -> Result<
    std::collections::HashMap<String, serde_json::Value>,
    Error<GetApiV1WorkspacesByIdVisitorsCountriesError>,
> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_id = id;

    let uri_str = format!(
        "{}/api/v1/workspaces/{id}/visitors/countries",
        configuration.base_path,
        id = crate::apis::urlencode(p_path_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `std::collections::HashMap&lt;String, serde_json::Value&gt;`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `std::collections::HashMap&lt;String, serde_json::Value&gt;`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetApiV1WorkspacesByIdVisitorsCountriesError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Get list of companies excluded from visitor analytics for this workspace.
pub async fn get_api_v1_workspaces_by_id_visitors_excluded_companies(
    configuration: &configuration::Configuration,
    id: &str,
) -> Result<
    std::collections::HashMap<String, serde_json::Value>,
    Error<GetApiV1WorkspacesByIdVisitorsExcludedCompaniesError>,
> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_id = id;

    let uri_str = format!(
        "{}/api/v1/workspaces/{id}/visitors/excluded-companies",
        configuration.base_path,
        id = crate::apis::urlencode(p_path_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `std::collections::HashMap&lt;String, serde_json::Value&gt;`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `std::collections::HashMap&lt;String, serde_json::Value&gt;`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetApiV1WorkspacesByIdVisitorsExcludedCompaniesError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Get aggregated visitor statistics including country distribution, company detection, and security flags.
pub async fn get_api_v1_workspaces_by_id_visitors_stats(
    configuration: &configuration::Configuration,
    id: &str,
    days: Option<&str>,
) -> Result<
    std::collections::HashMap<String, serde_json::Value>,
    Error<GetApiV1WorkspacesByIdVisitorsStatsError>,
> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_id = id;
    let p_query_days = days;

    let uri_str = format!(
        "{}/api/v1/workspaces/{id}/visitors/stats",
        configuration.base_path,
        id = crate::apis::urlencode(p_path_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_days {
        req_builder = req_builder.query(&[("days", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `std::collections::HashMap&lt;String, serde_json::Value&gt;`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `std::collections::HashMap&lt;String, serde_json::Value&gt;`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetApiV1WorkspacesByIdVisitorsStatsError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Track a visitor by IP address. IP is auto-extracted from request headers (CF-Connecting-IP > X-Forwarded-For > X-Real-IP) if not provided. Enriches with ipapi.is data and stores in database. Optionally tracks UTM parameters. Designed for landing page integration.
pub async fn post_api_v1_visitors_track(
    configuration: &configuration::Configuration,
    post_api_v1_visitors_track_request: models::PostApiV1VisitorsTrackRequest,
) -> Result<std::collections::HashMap<String, serde_json::Value>, Error<PostApiV1VisitorsTrackError>>
{
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_post_api_v1_visitors_track_request = post_api_v1_visitors_track_request;

    let uri_str = format!("{}/api/v1/visitors/track", configuration.base_path);
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_post_api_v1_visitors_track_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `std::collections::HashMap&lt;String, serde_json::Value&gt;`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `std::collections::HashMap&lt;String, serde_json::Value&gt;`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<PostApiV1VisitorsTrackError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Add a company domain to the exclusion list for visitor analytics.
pub async fn post_api_v1_workspaces_by_id_visitors_excluded_companies(
    configuration: &configuration::Configuration,
    id: &str,
    request_body: std::collections::HashMap<String, serde_json::Value>,
) -> Result<
    std::collections::HashMap<String, serde_json::Value>,
    Error<PostApiV1WorkspacesByIdVisitorsExcludedCompaniesError>,
> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_id = id;
    let p_body_request_body = request_body;

    let uri_str = format!(
        "{}/api/v1/workspaces/{id}/visitors/excluded-companies",
        configuration.base_path,
        id = crate::apis::urlencode(p_path_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_request_body);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `std::collections::HashMap&lt;String, serde_json::Value&gt;`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `std::collections::HashMap&lt;String, serde_json::Value&gt;`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<PostApiV1WorkspacesByIdVisitorsExcludedCompaniesError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Add and/or remove multiple companies from exclusion list in one request. Useful for the exclusion settings modal.
pub async fn post_api_v1_workspaces_by_id_visitors_excluded_companies_bulk(
    configuration: &configuration::Configuration,
    id: &str,
    request_body: std::collections::HashMap<String, serde_json::Value>,
) -> Result<
    std::collections::HashMap<String, serde_json::Value>,
    Error<PostApiV1WorkspacesByIdVisitorsExcludedCompaniesBulkError>,
> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_id = id;
    let p_body_request_body = request_body;

    let uri_str = format!(
        "{}/api/v1/workspaces/{id}/visitors/excluded-companies/bulk",
        configuration.base_path,
        id = crate::apis::urlencode(p_path_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_request_body);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `std::collections::HashMap&lt;String, serde_json::Value&gt;`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `std::collections::HashMap&lt;String, serde_json::Value&gt;`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<PostApiV1WorkspacesByIdVisitorsExcludedCompaniesBulkError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Creates leads from filtered visitors (noise filtered + excluded companies) and adds them to a customer group. Group is auto-created if it doesn't exist.
pub async fn post_api_v1_workspaces_by_id_visitors_sync_to_leads(
    configuration: &configuration::Configuration,
    id: &str,
    request_body: std::collections::HashMap<String, serde_json::Value>,
) -> Result<
    std::collections::HashMap<String, serde_json::Value>,
    Error<PostApiV1WorkspacesByIdVisitorsSyncToLeadsError>,
> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_id = id;
    let p_body_request_body = request_body;

    let uri_str = format!(
        "{}/api/v1/workspaces/{id}/visitors/sync-to-leads",
        configuration.base_path,
        id = crate::apis::urlencode(p_path_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_request_body);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `std::collections::HashMap&lt;String, serde_json::Value&gt;`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `std::collections::HashMap&lt;String, serde_json::Value&gt;`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<PostApiV1WorkspacesByIdVisitorsSyncToLeadsError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
